import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/footer";






export const metadata: Metadata = {
  title: "MakeenAcademy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
    
        className={`antialiased font-[Kalameh] bg-[#F9F9F9]`}
      >
        <Navbar/>
        {children}
       <Footer/>
      </body>
    </html>
  );
}
