import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "MakeenAcademy",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" >
      <body
    
        className={`antialiased font-[Kalameh] bg-[#F9F9F9]`}
      >
     
        {children}
    
      </body>
    </html>
  );
}
